### ISSUE TITLE
mcolon does not work when last indices are equal

### ISSUE THREAD

**Issue by rbe051** [pmgbergen/porepy#11]
>>> indPtr = np.array([1,5,5,6])
>>> select = np.array([0,1,2])
>>> mcolon(indPtr[select], indPtr[select + 1]) # OK

>>> select = np.array([0,1])
>>> mcolon(indPtr[select], indPtr[select + 1]) # Crashes

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/runar/uib/porepy/src/porepy/utils/mcolon.py", line 59, in mcolon
    print(n, 'n')

**Comment by rbe051** [comment]
Seems to work fine now
